# Generated by Django 3.1.3 on 2021-12-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('cno', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_bisnum', models.IntegerField(null=True)),
                ('expiration_date', models.DateTimeField()),
                ('company_status', models.CharField(max_length=1)),
                ('company_address', models.CharField(max_length=30)),
                ('company_telno', models.CharField(max_length=30)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_note', models.TextField(null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
